version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:5007"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

